@startuml

hide members
class Equity #lightgreen
class Photo #lightgreen
class Agent #lightgreen
class Customer #lightgreen
class Request #lightgreen

Equity <-- Photo: of
Equity --> Customer : ownedBy
Equity --> Agent : responsible

Meeting --> Agent : scheduledBy
Meeting --> Customer : attends
Meeting --> Equity : at

Request --> Equity : about
Request --> Customer : issuedBy
Request --> Agent : assignedTo

@enduml