@startuml
hide members
class Equity

Equity --> Owner : ownedBy
Equity <-- Photo: of
Agency -> Equity : exposedBy
Equity <-- Agent : worksWith
Agent -> Agency : employedBy
Agent --> Meeting : scheduledBy
Customer --> Meeting : attends
Meeting --> Equity : at
Agent <- Customer : contacted

@enduml