@startuml

object Equity
object Agent
object Customer1 #lightgreen {
    seller
}
object Customer2 #lightblue {
    buyer
}
object Request1 #lightgreen{
    type: SELL
}
object Request2 #lightblue {
    type: BUY
}
object Meeting
object Comment

Equity --> Customer1 : ownedBy
Equity --> Agent : responsible

Request1 --> Equity : about
Request1 --> Customer1 : issuedBy
Request1 --> Agent : assignedTo

Request2 --> Equity : about
Request2 --> Customer2 : issuedBy
Request2 --> Agent : assignedTo

Meeting --> Equity : at
Meeting --> Request2 : from
Meeting --> Customer2 : attends
Meeting --> Agent : scheduledBy

Comment -> Customer2: createdBy
Comment --> Equity : about
@enduml